-- Migration 002 — Table users (médecins)
CREATE TABLE IF NOT EXISTS users (
    id                     INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    hospital_id            INT UNSIGNED DEFAULT NULL,
    nom                    VARCHAR(80)  NOT NULL,
    prenom                 VARCHAR(80)  NOT NULL,
    email                  VARCHAR(150) NOT NULL UNIQUE,
    password               VARCHAR(255) NOT NULL,
    telephone              VARCHAR(25)  DEFAULT NULL,
    specialite             VARCHAR(100) DEFAULT NULL,
    numero_ordre           VARCHAR(50)  DEFAULT NULL,
    role                   ENUM('medecin','admin') NOT NULL DEFAULT 'medecin',
    avatar                 VARCHAR(255) DEFAULT NULL,
    is_active              TINYINT(1)  NOT NULL DEFAULT 0,
    email_verified_at      DATETIME    DEFAULT NULL,
    remember_token         VARCHAR(100) DEFAULT NULL,
    reset_token            VARCHAR(64)  DEFAULT NULL,
    reset_token_expires_at DATETIME    DEFAULT NULL,
    last_login_at          DATETIME    DEFAULT NULL,
    last_login_ip          VARCHAR(45)  DEFAULT NULL,
    created_at             DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at             DATETIME    DEFAULT NULL,
    INDEX idx_email    (email),
    INDEX idx_role     (role),
    INDEX idx_active   (is_active),
    INDEX idx_hospital (hospital_id),
    CONSTRAINT fk_user_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
