-- Migration 003 — Table detections (analyses CT Scan)
CREATE TABLE IF NOT EXISTS detections (
    id                   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id              INT UNSIGNED NOT NULL,
    patient_nom          VARCHAR(80)  NOT NULL,
    patient_prenom       VARCHAR(80)  NOT NULL,
    patient_age          TINYINT UNSIGNED DEFAULT NULL,
    patient_sexe         ENUM('M','F','Autre') DEFAULT NULL,
    patient_code         VARCHAR(50)  DEFAULT NULL,
    image_path           VARCHAR(500) NOT NULL,
    image_original_name  VARCHAR(255) DEFAULT NULL,
    image_size           INT UNSIGNED DEFAULT NULL,
    image_hash           VARCHAR(64)  DEFAULT NULL,
    result_type          ENUM('normal','suspect','cancereux','inconnu') NOT NULL DEFAULT 'inconnu',
    confidence_score     DECIMAL(5,2) DEFAULT NULL,
    stage                ENUM('I','II','III','IV') DEFAULT NULL,
    regions_json         JSON         DEFAULT NULL,
    model_version        VARCHAR(20)  DEFAULT '1.0',
    processing_time_ms   INT UNSIGNED DEFAULT NULL,
    notes_medecin        TEXT         DEFAULT NULL,
    is_reviewed          TINYINT(1)  NOT NULL DEFAULT 0,
    status               ENUM('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
    created_at           DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at           DATETIME    DEFAULT NULL,
    INDEX idx_user_id    (user_id),
    INDEX idx_result     (result_type),
    INDEX idx_created    (created_at),
    INDEX idx_hash       (image_hash),
    INDEX idx_status     (status),
    CONSTRAINT fk_det_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
